ifneq ($(ENV),WIN32)
#CCFLAGS=-O2 -I/usr/src -DLINUX
CCFLAGS=-O2 -DLINUX -Wno-narrowing -Wno-unused-result $(shell pkg-config --cflags libusb-1.0)
EXT=
DEL=rm -f
DEST=
CC=g++
else
CC=gcc
CCFLAGS=-O2 -I. -DWIN32 -Wall -Llib/gcc
EXT=.exe
DEL=@del
DEST=win32-bin/
endif
LDFLAGS=-lusb-1.0

all: s1giveio/s1giveio

include common/make.inc.mk
include s1giveio/make.inc.mk

clean: clean_common clean_s1giveio
